### ISSUE TITLE
Extend the helm chart so that users can fully configure fiaas-deploy-daemon when installing Skipper

### ISSUE THREAD

**Issue by mortenlj** [fiaas/skipper#89]
Currently we provide a way to create a simplified configmap for fiaas-deploy-daemon when installing Skipper.

This should be extended, so that users can install Skipper and fully configure fiaas-deploy-daemon at the same time if they wish. It should still be possible to skip creation of the fiaas-deploy-daemon configmap if the user has a different mechanism for doing this.

**Comment by oyvindio** [comment]
Maybe making `cluster_config.yaml` in the configmap overridable via a value on the helm chart can be a solution to this

**Comment by oyvindio** [comment]
Fixed by #91
